# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-17 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180531_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_title',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='room_picture',
        ),
    ]
