# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-18 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20181218_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='room_picture1',
            field=models.FileField(default=False, upload_to=b''),
        ),
        migrations.AddField(
            model_name='album',
            name='room_picture2',
            field=models.FileField(default=False, upload_to=b''),
        ),
    ]
